### ISSUE TITLE
Cannot login into Aula Global

### ISSUE THREAD

**Issue by PaquitoelChocolatero** [tairosonloa/Aula_Global_UC3M#3]
Due to the recent update to moodle 3.5 the script fails to get user token. It reports that username or password are not correct.

**Comment by tairosonloa** [comment]
It looks like the API login feature has been closed, or the service name has changed. I'll ask the IT department on the Monday morning.

**Comment by tairosonloa** [comment]
The IT department answered me that the service `ag_mobile`, which is used by the script to login users, is not longer available ([see this Twitter thread in Spanish](https://twitter.com/sdic_uc3m/status/1173965060278034434?s=20)). There is nothing to do right now.
