### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by javilonso** [tairosonloa/Aula_Global_UC3M#5]
Acabo de ver que lo arreglaste y el login lo hace perfecto. Empieza a descargar pero me ha dado este fallo. Echale un ojo si puedes, sin prisa. Gracias crack. Pasa pp que te invito a una cerve ;)
```
	Downloading: presentacion-en.pdf
	Downloading: template_en.ods
Traceback (most recent call last):
  File "aulaglobal.py", line 90, in <module>
    value, params = cgi.parse_header(cdheader)
  File "/usr/lib/python3.7/cgi.py", line 243, in parse_header
    parts = _parseparam(';' + line)
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by tairosonloa** [comment]
Perdonad, que he estado bastante liado. Acabo de mergear la PR #6 de Guille. Con los cursos que tengo yo en Aula Global no soy capaz de replicar yo el error, por lo que no puedo arreglarlo sin ayuda.

**Comment by javilonso** [comment]
Cierro issue, ya funciona a la perfeccion :)

Gracias!
