### ISSUE TITLE
Conflict with Forbidden Characters on Windows

### ISSUE THREAD

**Issue by Vallahar** [tairosonloa/Aula_Global_UC3M#8]
Hi!

I was using this script to get all my files from aulaglobal, but this course some titles appear with asterisks on their titles. 

This is the error message I was encountering:

![image](https://user-images.githubusercontent.com/18752703/94808754-e346c600-03f1-11eb-934c-4e9ed99f6934.png)

I fixed it adding the following lines before the part that create the folders with the subject's names, specifically in line 89.

```python
# Clean unsupported Windows namefile characters
        unsupportedChars = '<>:"/|\\\*?'
        for char in unsupportedChars:
            if char in h1:
                charIndex = h1.index(char)
                h1 = h1[:charIndex] + h1[charIndex + 1:]
```

I'm not sure if this is the right way to contribute to the GitHub repository though, as I have little knowledge about how this works, but hey, hope this helps!

**Comment by tairosonloa** [comment]
Hi @Vallahar,

You can [fork this repository](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-forks) by clicking on the "Fork" button on the right up corner. Then **create a new git branch** and make there the code changes. After that, you can [open a Pull Request to this repo](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

If the code changes are helpful, like fixing bugs or making the script usage easiest, I'll accept them and you will be shown as a contributor in the main page of the repository (the column on the right). I encourage you to do so. I saw you are a newbie, and I think this is a good chance to you to learn how to contribute to free software on GitHub ;)

Also, now that October has started, it's time to [hacktoberfest](https://hacktoberfest.digitalocean.com/)!! Your PR to this repo will count to your hacktoberfest contributions if you register there.

Best regards!
Aitor

**Comment by Vallahar** [comment]
Thanks for the detailed answer!

I had no idea about the Hacktoberfest iniciative, I'm certainly going to try and get that t-shirt haha.

Pull request made, thanks for the encouragement, I appreciated it. 

Cheers!
Fernando
